NSArray+Difference: handle nil and non-array arguments.
Lightricks/expecta pull request #14
Opened 2021-02-07 08:14 UTC by arangato

Raising from differenceFrom has negative effect of disrupting tests and
makes getting to the mismatch harder. Therefore returning a descriptive
message for nil and non-array arguments.

2021-02-08 09:46 UTC, byohay requested changes
F&S.

2021-02-08 09:46 UTC, byohay commented on Expecta/NSArray+Difference.m
> +  if (![object isKindOfClass:NSArray.class]) {
`[NSArray class]`

2021-02-09 13:07 UTC, arangato commented
Fixed and squashed.

2021-02-10 10:39 UTC, byohay approved these changes
not related to this PR, but why is `NSArray+Difference` in expecta and other data structures are in Lightricks' private repo?

2021-02-10 10:54 UTC, arangato commented
> not related to this PR, but why is `NSArray+Difference` in expecta and other data structures are in Lightricks' private repo?

because of LLReactiveMatchers, which is a strange 3rd party that is part of Foundations. It uses LT Expecta fork and compares NSArrays

2021-02-10 11:57 UTC, merged